# Changes here will be overwritten by Copier
_commit: 80774b6
_src_path: /Users/pat/Projects/covenofchaos/templates/copier-pdm-asdf
author: pat laplante
email: laplante.patrick@gmail.com
module_name: mfamt_db_dump
project_description: mfamt_db_dump
project_name: mfamt_db_dump
python: asdf
python_version: '3.10'
use_pep_582: true

